package derekahedron.invexp.datagen.compat;

import derekahedron.invexp.datagen.InvExpItemTagProvider;
import derekahedron.invexp.item.InvExpItemTags;
import derekahedron.invexp.util.CompatUtil;

public class CataclysmItemTagsProvider extends CompatibilityItemTagsProvider {

    public CataclysmItemTagsProvider(InvExpItemTagProvider provider) {
        super(provider);
    }

    @Override
    public void makeTags() {
        tag(InvExpItemTags.SackType.WOOD)
                .addOptional(CompatUtil.cataclysm("chorus_stem"));
        tag(InvExpItemTags.SackType.STONE)
                .addOptional(CompatUtil.cataclysm("dungeon_block"))
                .addOptional(CompatUtil.cataclysm("polished_end_stone"))
                .addOptional(CompatUtil.cataclysm("polished_end_stone_slab"))
                .addOptional(CompatUtil.cataclysm("polished_end_stone_stairs"))
                .addOptional(CompatUtil.cataclysm("chiseled_end_stone_bricks"))
                .addOptional(CompatUtil.cataclysm("end_stone_pillar"))
                .addOptional(CompatUtil.cataclysm("void_infused_end_stone_bricks"))
                .addOptional(CompatUtil.cataclysm("void_stone"))
                .addOptional(CompatUtil.cataclysm("obsidian_bricks"))
                .addOptional(CompatUtil.cataclysm("obsidian_brick_slab"))
                .addOptional(CompatUtil.cataclysm("obsidian_brick_stairs"))
                .addOptional(CompatUtil.cataclysm("obsidian_brick_wall"))
                .addOptional(CompatUtil.cataclysm("polished_obsidian"))
                .addOptional(CompatUtil.cataclysm("chiseled_obsidian_bricks"))
                .addOptional(CompatUtil.cataclysm("stone_pillar"))
                .addOptional(CompatUtil.cataclysm("chiseled_stone_brick_pillar"))
                .addOptional(CompatUtil.cataclysm("stone_tiles"))
                .addOptional(CompatUtil.cataclysm("stone_tile_slab"))
                .addOptional(CompatUtil.cataclysm("stone_tile_stairs"))
                .addOptional(CompatUtil.cataclysm("stone_tile_wall"))
                .addOptional(CompatUtil.cataclysm("blackstone_pillar"))
                .addOptional(CompatUtil.cataclysm("azure_seastone"))
                .addOptional(CompatUtil.cataclysm("azure_seastone_slab"))
                .addOptional(CompatUtil.cataclysm("azure_seastone_stairs"))
                .addOptional(CompatUtil.cataclysm("azure_seastone_wall"))
                .addOptional(CompatUtil.cataclysm("azure_seastone_fence"))
                .addOptional(CompatUtil.cataclysm("azure_seastone_tiles"))
                .addOptional(CompatUtil.cataclysm("chiseled_azure_seastone"))
                .addOptional(CompatUtil.cataclysm("azure_seastone_bricks"))
                .addOptional(CompatUtil.cataclysm("azure_seastone_brick_slab"))
                .addOptional(CompatUtil.cataclysm("azure_seastone_brick_stairs"))
                .addOptional(CompatUtil.cataclysm("azure_seastone_brick_wall"))
                .addOptional(CompatUtil.cataclysm("polished_azure_seastone"))
                .addOptional(CompatUtil.cataclysm("polished_azure_seastone_slab"))
                .addOptional(CompatUtil.cataclysm("polished_azure_seastone_stairs"))
                .addOptional(CompatUtil.cataclysm("polished_azure_seastone_wall"))
                .addOptional(CompatUtil.cataclysm("azure_seastone_pillar"))
                .addOptional(CompatUtil.cataclysm("azure_seastone_pillar_wall"))
                .addOptional(CompatUtil.cataclysm("chiseled_azure_seastone_pillar"))
                .addOptional(CompatUtil.cataclysm("chiseled_azure_seastone_pillar_wall"))
                .addOptional(CompatUtil.cataclysm("frosted_stone_bricks"))
                .addOptional(CompatUtil.cataclysm("frosted_stone_brick_slab"))
                .addOptional(CompatUtil.cataclysm("frosted_stone_brick_stairs"))
                .addOptional(CompatUtil.cataclysm("frosted_stone_brick_wall"));
        tag(InvExpItemTags.SackType.SANDSTONE)
                .addOptional(CompatUtil.cataclysm("polished_sandstone"))
                .addOptional(CompatUtil.cataclysm("sandstone_falling_trap"));
        tag(InvExpItemTags.SackType.PRISMARINE)
                .addOptional(CompatUtil.cataclysm("prismarine_brick_fence"))
                .addOptional(CompatUtil.cataclysm("prismarine_brick_wall"));
        tag(InvExpItemTags.SackType.PURPUR)
                .addOptional(CompatUtil.cataclysm("chiseled_purpur_block"))
                .addOptional(CompatUtil.cataclysm("purpur_wall"));
        tag(InvExpItemTags.SackType.METAL_BLOCK)
                .addOptional(CompatUtil.cataclysm("enderite_block"))
                .addOptional(CompatUtil.cataclysm("witherite_block"))
                .addOptional(CompatUtil.cataclysm("ignitium_block"))
                .addOptional(CompatUtil.cataclysm("ancient_metal_block"))
                .addOptional(CompatUtil.cataclysm("cursium_block"))
                .addOptional(CompatUtil.cataclysm("black_steel_block"))
                .addOptional(CompatUtil.cataclysm("black_steel_fence"))
                .addOptional(CompatUtil.cataclysm("black_steel_wall"));
        tag(InvExpItemTags.SackType.CRYSTAL_BLOCK)
                .addOptional(CompatUtil.cataclysm("quartz_brick_wall"))
                .addOptional(CompatUtil.cataclysm("void_crystal"))
                .addOptional(CompatUtil.cataclysm("void_lantern_block"));
        tag(InvExpItemTags.SackType.ICE)
                .addOptional(CompatUtil.cataclysm("pointed_icicle"));
        tag(InvExpItemTags.SackType.ORE)
                .addOptional(CompatUtil.cataclysm("witherite_ingot"))
                .addOptional(CompatUtil.cataclysm("ancient_metal_ingot"))
                .addOptional(CompatUtil.cataclysm("ancient_metal_nugget"))
                .addOptional(CompatUtil.cataclysm("black_steel_ingot"))
                .addOptional(CompatUtil.cataclysm("black_steel_nugget"))
                .addOptional(CompatUtil.cataclysm("ignitium_ingot"))
                .addOptional(CompatUtil.cataclysm("cursium_ingot"));
        tag(InvExpItemTags.SackType.HEAD)
                .addOptional(CompatUtil.cataclysm("aptrgangr_head"))
                .addOptional(CompatUtil.cataclysm("draugr_head"))
                .addOptional(CompatUtil.cataclysm("kobolediator_skull"));
        tag(InvExpItemTags.SackType.REDSTONE_COMPONENT)
                .addOptional(CompatUtil.cataclysm("sandstone_poison_dart_trap"))
                .addOptional(CompatUtil.cataclysm("sandstone_ignite_trap"))
                .addOptional(CompatUtil.cataclysm("purpur_void_rune_trap_block"))
                .addOptional(CompatUtil.cataclysm("end_stone_teleport_trap_bricks"))
                .addOptional(CompatUtil.cataclysm("obsidian_explosion_trap_bricks"));
        tag(InvExpItemTags.SackType.FOOD)
                .addOptional(CompatUtil.cataclysm("amethyst_crab_meat"))
                .addOptional(CompatUtil.cataclysm("blessed_amethyst_crab_meat"));
        tag(InvExpItemTags.SackType.RAW_FISH)
                .addOptional(CompatUtil.cataclysm("lionfish"));
        tag(InvExpItemTags.SackType.CREATURE)
                .addOptional(CompatUtil.cataclysm("monstrous_horn"))
                .addOptional(CompatUtil.cataclysm("lava_power_cell"))
                .addOptional(CompatUtil.cataclysm("dying_ember"))
                .addOptional(CompatUtil.cataclysm("koboleton_bone"))
                .addOptional(CompatUtil.cataclysm("crystallized_coral_fragments"))
                .addOptional(CompatUtil.cataclysm("coral_chunk"))
                .addOptional(CompatUtil.cataclysm("amethyst_crab_shell"));
        tag(InvExpItemTags.SackType.SMITHING_TEMPLATE)
                .addOptional(CompatUtil.cataclysm("ignitium_upgrade_smithing_template"))
                .addOptional(CompatUtil.cataclysm("cursium_upgrade_smithing_template"));

        tag(InvExpItemTags.SackWeight.FIFTH)
                .addOptional(CompatUtil.cataclysm("ancient_metal_nugget"))
                .addOptional(CompatUtil.cataclysm("black_steel_nugget"));
        tag(InvExpItemTags.SackWeight.HALF)
                .addOptional(CompatUtil.cataclysm("stone_tile_slab"))
                .addOptional(CompatUtil.cataclysm("azure_seastone_slab"))
                .addOptional(CompatUtil.cataclysm("azure_seastone_brick_slab"))
                .addOptional(CompatUtil.cataclysm("polished_azure_seastone_slab"))
                .addOptional(CompatUtil.cataclysm("frosted_stone_brick_slab"));
    }
}
