package derekahedron.invexp.datagen.compat;

import derekahedron.invexp.datagen.InvExpItemTagProvider;
import derekahedron.invexp.item.InvExpItemTags;
import derekahedron.invexp.util.CompatUtil;

public class ForgeItemTagsProvider extends CompatibilityItemTagsProvider {

    public ForgeItemTagsProvider(InvExpItemTagProvider provider) {
        super(provider);
    }

    @Override
    public void makeTags() {
        tag(InvExpItemTags.SackType.METAL_BLOCK)
                .addOptionalTag(CompatUtil.forge("storage_blocks/tin"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/aluminum"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/aluminium"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/lead"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/nickel"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/silver"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/zinc"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/bronze"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/brass"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/steel"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/constantan"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/electrum"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/uranium"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/osmium"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/cobalt"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/andesite_alloy"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/neodymium"));
        tag(InvExpItemTags.SackType.CRYSTAL_BLOCK)
                .addOptionalTag(CompatUtil.forge("storage_blocks/fluorite"));
        tag(InvExpItemTags.SackType.ORE)
                .addOptionalTag(CompatUtil.forge("raw_materials/tin"))
                .addOptionalTag(CompatUtil.forge("raw_materials/aluminum"))
                .addOptionalTag(CompatUtil.forge("raw_materials/aluminium"))
                .addOptionalTag(CompatUtil.forge("raw_materials/lead"))
                .addOptionalTag(CompatUtil.forge("raw_materials/nickel"))
                .addOptionalTag(CompatUtil.forge("raw_materials/silver"))
                .addOptionalTag(CompatUtil.forge("raw_materials/zinc"))
                .addOptionalTag(CompatUtil.forge("raw_materials/uranium"))
                .addOptionalTag(CompatUtil.forge("raw_materials/osmium"))
                .addOptionalTag(CompatUtil.forge("raw_materials/cobalt"))
                .addOptionalTag(CompatUtil.forge("ingots/tin"))
                .addOptionalTag(CompatUtil.forge("ingots/aluminum"))
                .addOptionalTag(CompatUtil.forge("ingots/aluminium"))
                .addOptionalTag(CompatUtil.forge("ingots/lead"))
                .addOptionalTag(CompatUtil.forge("ingots/nickel"))
                .addOptionalTag(CompatUtil.forge("ingots/silver"))
                .addOptionalTag(CompatUtil.forge("ingots/zinc"))
                .addOptionalTag(CompatUtil.forge("ingots/bronze"))
                .addOptionalTag(CompatUtil.forge("ingots/brass"))
                .addOptionalTag(CompatUtil.forge("ingots/steel"))
                .addOptionalTag(CompatUtil.forge("ingots/constantan"))
                .addOptionalTag(CompatUtil.forge("ingots/electrum"))
                .addOptionalTag(CompatUtil.forge("ingots/uranium"))
                .addOptionalTag(CompatUtil.forge("ingots/osmium"))
                .addOptionalTag(CompatUtil.forge("ingots/cobalt"))
                .addOptionalTag(CompatUtil.forge("ingots/manganese"))
                .addOptionalTag(CompatUtil.forge("ingots/shaka"))
                .addOptionalTag(CompatUtil.forge("nuggets/copper"))
                .addOptionalTag(CompatUtil.forge("nuggets/netherite_scrap"))
                .addOptionalTag(CompatUtil.forge("nuggets/netherite"))
                .addOptionalTag(CompatUtil.forge("nuggets/tin"))
                .addOptionalTag(CompatUtil.forge("nuggets/aluminum"))
                .addOptionalTag(CompatUtil.forge("nuggets/aluminium"))
                .addOptionalTag(CompatUtil.forge("nuggets/lead"))
                .addOptionalTag(CompatUtil.forge("nuggets/nickel"))
                .addOptionalTag(CompatUtil.forge("nuggets/silver"))
                .addOptionalTag(CompatUtil.forge("nuggets/zinc"))
                .addOptionalTag(CompatUtil.forge("nuggets/bronze"))
                .addOptionalTag(CompatUtil.forge("nuggets/brass"))
                .addOptionalTag(CompatUtil.forge("nuggets/steel"))
                .addOptionalTag(CompatUtil.forge("nuggets/constantan"))
                .addOptionalTag(CompatUtil.forge("nuggets/electrum"))
                .addOptionalTag(CompatUtil.forge("nuggets/uranium"))
                .addOptionalTag(CompatUtil.forge("nuggets/osmium"))
                .addOptionalTag(CompatUtil.forge("nuggets/cobalt"))
                .addOptionalTag(CompatUtil.forge("gems/fluorite"))
                .addOptionalTag(CompatUtil.forge("gems/eudialyte"))
                .addOptionalTag(CompatUtil.forge("gems/azurite"))
                .addOptionalTag(CompatUtil.forge("gems/zircon"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/raw_nickel"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/raw_silver"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/raw_zinc"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/raw_cobalt"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/raw_uranium"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/pearl"));
        tag(InvExpItemTags.SackType.CARROT)
                .addOptionalTag(CompatUtil.forge("storage_blocks/carrot"));
        tag(InvExpItemTags.SackType.POTATO)
                .addOptionalTag(CompatUtil.forge("storage_blocks/potato"));
        tag(InvExpItemTags.SackType.BEETROOT)
                .addOptionalTag(CompatUtil.forge("storage_blocks/beetroot"));

        // Extra Sack Types
        provider.tag(InvExpItemTags.SackType.CABBAGE)
                .addOptionalTag(CompatUtil.forge("storage_blocks/cabbage"))
                .addOptionalTag(CompatUtil.forge("crops/cabbage"));
        provider.tag(InvExpItemTags.SackType.CABBAGE_SEEDS)
                .addOptionalTag(CompatUtil.forge("seeds/cabbage"));
        provider.tag(InvExpItemTags.SackType.TOMATO)
                .addOptionalTag(CompatUtil.forge("storage_blocks/tomato"))
                .addOptionalTag(CompatUtil.forge("crops/tomato"));
        provider.tag(InvExpItemTags.SackType.TOMATO_SEEDS)
                .addOptionalTag(CompatUtil.forge("seeds/tomato"));
        provider.tag(InvExpItemTags.SackType.ONION)
                .addOptionalTag(CompatUtil.forge("storage_blocks/onion"))
                .addOptionalTag(CompatUtil.forge("crops/onion"));
        provider.tag(InvExpItemTags.SackType.RICE)
                .addOptionalTag(CompatUtil.forge("storage_blocks/rice"))
                .addOptionalTag(CompatUtil.forge("crops/rice"));
        provider.tag(InvExpItemTags.SackType.CANTALOUPE_SEEDS)
                .addOptionalTag(CompatUtil.forge("seeds/cantaloupe"));
        provider.tag(InvExpItemTags.SackType.SALMONBERRIES)
                .addOptionalTag(CompatUtil.forge("storage_blocks/salmonberries"))
                .addOptionalTag(CompatUtil.forge("storage_blocks/salmonberry"))
                .addOptionalTag(CompatUtil.forge("fruits/salmonberries"))
                .addOptionalTag(CompatUtil.forge("fruits/salmonberry"))
                .addOptionalTag(CompatUtil.forge("crops/salmonberries"))
                .addOptionalTag(CompatUtil.forge("crops/salmonberry"));
        provider.tag(InvExpItemTags.SackType.SALMONBERRY_SEEDS)
                .addOptionalTag(CompatUtil.forge("seeds/salmonberries"))
                .addOptionalTag(CompatUtil.forge("seeds/salmonberry"));
        provider.tag(InvExpItemTags.SackType.METAL_PLATE)
                .addOptionalTag(CompatUtil.forge("plates/copper"))
                .addOptionalTag(CompatUtil.forge("plates/iron"))
                .addOptionalTag(CompatUtil.forge("plates/gold"))
                .addOptionalTag(CompatUtil.forge("plates/tin"))
                .addOptionalTag(CompatUtil.forge("plates/aluminum"))
                .addOptionalTag(CompatUtil.forge("plates/aluminium"))
                .addOptionalTag(CompatUtil.forge("plates/lead"))
                .addOptionalTag(CompatUtil.forge("plates/nickel"))
                .addOptionalTag(CompatUtil.forge("plates/silver"))
                .addOptionalTag(CompatUtil.forge("plates/zinc"))
                .addOptionalTag(CompatUtil.forge("plates/bronze"))
                .addOptionalTag(CompatUtil.forge("plates/brass"))
                .addOptionalTag(CompatUtil.forge("plates/steel"))
                .addOptionalTag(CompatUtil.forge("plates/electrum"))
                .addOptionalTag(CompatUtil.forge("plates/uranium"))
                .addOptionalTag(CompatUtil.forge("plates/osmium"))
                .addOptionalTag(CompatUtil.forge("plates/cobalt"));

        provider.tag(InvExpItemTags.SackWeight.FIFTH)
                .addOptionalTag(CompatUtil.forge("nuggets/copper"))
                .addOptionalTag(CompatUtil.forge("nuggets/netherite_scrap"))
                .addOptionalTag(CompatUtil.forge("nuggets/netherite"))
                .addOptionalTag(CompatUtil.forge("nuggets/tin"))
                .addOptionalTag(CompatUtil.forge("nuggets/aluminum"))
                .addOptionalTag(CompatUtil.forge("nuggets/aluminium"))
                .addOptionalTag(CompatUtil.forge("nuggets/lead"))
                .addOptionalTag(CompatUtil.forge("nuggets/nickel"))
                .addOptionalTag(CompatUtil.forge("nuggets/silver"))
                .addOptionalTag(CompatUtil.forge("nuggets/zinc"))
                .addOptionalTag(CompatUtil.forge("nuggets/bronze"))
                .addOptionalTag(CompatUtil.forge("nuggets/brass"))
                .addOptionalTag(CompatUtil.forge("nuggets/steel"))
                .addOptionalTag(CompatUtil.forge("nuggets/electrum"))
                .addOptionalTag(CompatUtil.forge("nuggets/uranium"))
                .addOptionalTag(CompatUtil.forge("nuggets/osmium"))
                .addOptionalTag(CompatUtil.forge("nuggets/cobalt"));
        provider.tag(InvExpItemTags.SackWeight.FOURTH)
                .addOptionalTag(CompatUtil.forge("seeds/cabbage"))
                .addOptionalTag(CompatUtil.forge("seeds/tomato"))
                .addOptionalTag(CompatUtil.forge("seeds/cantaloupe"))
                .addOptionalTag(CompatUtil.forge("seeds/salmonberries"))
                .addOptionalTag(CompatUtil.forge("seeds/salmonberry"));
        provider.tag(InvExpItemTags.SackWeight.HALF)
                .addOptionalTag(CompatUtil.forge("crops/cabbage"))
                .addOptionalTag(CompatUtil.forge("crops/tomato"))
                .addOptionalTag(CompatUtil.forge("crops/onion"))
                .addOptionalTag(CompatUtil.forge("crops/rice"))
                .addOptionalTag(CompatUtil.forge("fruits/salmonberries"))
                .addOptionalTag(CompatUtil.forge("fruits/salmonberry"))
                .addOptionalTag(CompatUtil.forge("crops/salmonberries"))
                .addOptionalTag(CompatUtil.forge("crops/salmonberry"));
    }
}
